CREATE DATABASE IF NOT EXISTS ClientesDb;
USE ClientesDb;

CREATE TABLE IF NOT EXISTS Clientes (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    DataNascimento DATE NOT NULL,
    Cpf CHAR(11) NOT NULL UNIQUE,
    Email VARCHAR(150) NOT NULL,
    RendimentoAnual DECIMAL(15,2) NOT NULL,
    Estado CHAR(2) NOT NULL,
    Telefone VARCHAR(15) NOT NULL,
    Score INT NOT NULL,
    Classificacao VARCHAR(50) NOT NULL,
    DataCadastro DATETIME DEFAULT CURRENT_TIMESTAMP
);
